export const moviesData = [
  {
    movieTitle: "Iron Man (2008)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=8ugaeA-nMTc",
    releaseDate: "May 2, 2008",
  },
  {
    movieTitle: "The Incredible Hulk (2008)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=xbqNb2PFKKA",
    releaseDate: "June 13, 2008",
  },
  {
    movieTitle: "Iron Man 2 (2010)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=BoohRoVA9WQ",
    releaseDate: "May 7, 2010",
  },
  {
    movieTitle: "Thor (2011)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=JOddp-nlNvQ",
    releaseDate: "May 6, 2011",
  },
  {
    movieTitle: "Captain America: The First Avenger (2011)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=JerVrbLldXw",
    releaseDate: "July 22, 2011",
  },
  {
    movieTitle: "The Avengers (2012)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=eOrNdBpGMv8",
    releaseDate: "May 4, 2012",
  },
  {
    movieTitle: "Iron Man 3 (2013)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=Ke1Y3P9D0Bc",
    releaseDate: "May 3, 2013",
  },
  {
    movieTitle: "Thor: The Dark World (2013)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=npvJ9FTgZbM",
    releaseDate: "November 8, 2013",
  },
  {
    movieTitle: "Captain America: The Winter Soldier (2014)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=7SlILk2WMTI",
    releaseDate: "April 4, 2014",
  },
  {
    movieTitle: "Guardians of the Galaxy (2014)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=d96cjJhvlMA",
    releaseDate: "August 1, 2014",
  },
  {
    movieTitle: "Avengers: Age of Ultron (2015)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=tmeOjFno6Do",
    releaseDate: "May 1, 2015",
  },
  {
    movieTitle: "Ant-Man (2015)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=pWdKf3MneyI",
    releaseDate: "July 17, 2015",
  },
  {
    movieTitle: "Captain America: Civil War (2016)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=dKrVegVI0Us",
    releaseDate: "May 6, 2016",
  },
  {
    movieTitle: "Doctor Strange (2016)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=HSzx-zryEgM",
    releaseDate: "November 4, 2016",
  },
  {
    movieTitle: "Black Panther (2018)",
    poster: "Random Poster",
    trailerLink: "https://www.youtube.com/watch?v=xjDjIWPwcPU",
    releaseDate: "February 16, 2018",
  },
];
